spring:
  output:
    ansi:
      enabled: ALWAYS

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-local.ginterface.net:8761/eureka/
