server:
  port: 28080

spring:
  profiles:
    active: local

# Setting logging levels
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    net.genieworks.ginterface.product: DEBUG