server:
  port: 18888

spring:
  profiles:
    active: native
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: classpath:config/,classpath:config/eureka-server, classpath:config/product-server
