server:
  port: 8888

spring:
  profiles:
    active: native
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    config:
      server:
        bootstrap: true
        native:
          search-locations: classpath:config/,classpath:config/eureka-server, classpath:config/product-server

# Setting logging levels
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    net.genieworks.ginterface.config: DEBUG