#Default port is 8761
server:
  port: 8761

spring:
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
  serviceUrl:
    defaultZone: http://eureka-local.ginterface.net:8761

#Setting logging levels
logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    com.genieworks.ginterface.config: DEBUG